spring:
  application:
    name: credentials-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/${MONGO_DB}?authSource=admin

bling:
  api:
    url: https://api.bling.com.br/Api/v3
    client-id: ${BLING_CLIENT_ID}
    client-secret: ${BLING_CLIENT_SECRET}

server:
  port: 8082